### ISSUE TITLE
Setup project management on this github project

### ISSUE THREAD

**Issue by davidonlaptop** [GELOG/variantminer#8]
use waffle or zenhub

**Comment by iki-v** [comment]
Problèmes de droits pour la création d'espace : "Uh oh! Waffle needs an admin of GELOG/variantminer to configure webhooks, to enable real time updates from GitHub."

A priori, le droit d'admin est uniquement à owner : There is only one owner of a repository owned by a user account; this permission cannot be shared with another user account. To transfer ownership of a repository to another user, see "How to transfer a repository."

David, pourrai-tu reprendre le relais ?

**Comment by davidonlaptop** [comment]
j'ai cliqué pour configurer le webhook.
